name: Terraform Code Analysis
run-name: Terraform Code Auto-Validation Triggered by @${{ github.actor }}
permissions:
    id-token: write
    contents: read
    
on:
  pull_request:
    paths:
        - 'modules/azure/**/**.tf'
    types: [opened, reopened,synchronize, edited]

env:
  location: australiaeast

jobs:
  
  runPreMergeChecks:
    name: IaC Static Code Linting and Analysis
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        #with:
            #since_last_remote_commit: true 

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Get all doc and params files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            params:
              - '**.tf'

      - name: Run step if param file(s) change
        id: run-if-param-changed
       
        if: steps.changed-files-yaml.outputs.params_any_changed == 'true'  
        env:
          PARAMS_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.params_all_changed_files }}
          
        run: |
          echo "One or more PARAM file(s) has changed."
          echo "List all the files that have changed:"
          echo "$PARAMS_ALL_CHANGED_FILES"
          echo -e "Running TF Formart"
          echo -e "--------------------------------------------------------"
          echo -e "--------------------------------------------------------"
          for file in ${PARAMS_ALL_CHANGED_FILES}; do
            terraform fmt -write=false $file  # Run terraform fmt on the specific file
            echo -e "----------------------$((i))---------------------------------"
          done

      - name: Install tfsec from Official Repo
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Install tflint from Official Repo
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install required packages on GitHub runner via apt
        run: |

          echo "Updating APT and installing required packages..."

          sudo apt update && sudo apt upgrade -y

          sudo apt install --no-install-recommends -y \
            apt-transport-https \
            apt-utils \
            build-essential \
            curl \
            wget \
            git \
            gnupg \
            gpg \
            python3-crcmod \
            python3-dev \
            python3-pip \
            python3-virtualenv \
            shellcheck \
            unzip \
            zip \

          sudo apt autoremove --purge -y

          echo "Environment is ready!"

      - name: Install Checkov & YAML Lint
        run: |
          pip3 install --upgrade pip && pip3 install --upgrade setuptools
          pip3 install checkov
          pip3 install yamllint

      - name: Run TF Sec
        shell: bash
        run: |

          MODULES=$(find modules -type d -mindepth 2 -maxdepth 2 | tr '\n' ' ')
           for module in ${MODULES}; do
                echo -e $module
            done

          for dir in ${MODULES}; do
            if [ -f "$dir/main.tf" ]; then
              echo "Running tflint in $dir"
              tfsec $dir
            else
              echo "Skipping $dir — no main.tf found"
            fi
            echo "--------------------------------------------------------"
          done

          

      - name: Run TF Lint
        shell: bash
        run: |
          MODULES=$(find modules -type d -mindepth 2 -maxdepth 2 | tr '\n' ' ')
           for module in ${MODULES}; do
                echo -e $module
            done

          for dir in ${MODULES}; do
            if [ -f "$dir/main.tf" ]; then
              echo "Running lint in $dir"
              tflint --chdir="$dir"
            else
              echo "Skipping $dir — no main.tf found"
            fi
            echo "--------------------------------------------------------"
          done

      - name: Run TF Checkov
        shell: bash
        run: |
          MODULES=$(find modules -type d -mindepth 2 -maxdepth 2 | tr '\n' ' ')
           for module in ${MODULES}; do
                echo -e $module
            done

          for dir in ${MODULES}; do
            if [ -f "$dir/main.tf" ]; then
              echo "Running checkov in $dir"
              checkov --directory $dir
              tflint --chdir="$dir"
            else
              echo "Skipping $dir — no main.tf found"
            fi
            echo "--------------------------------------------------------"
          done

              
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'



      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'